# -*- coding: utf-8 -*-
"""Nakshatra deep-dive reference: deity, symbol, gana, and a short character note."""
NAK_DETAIL = {
 "Ashwini":{"deity":"Ashwini Kumaras","symbol":"Horse's head","gana":"Deva","trait":"quick, healing, pioneering"},
 "Bharani":{"deity":"Yama","symbol":"Yoni","gana":"Manushya","trait":"intense, disciplined, transformative"},
 "Krittika":{"deity":"Agni","symbol":"Razor/flame","gana":"Rakshasa","trait":"sharp, purifying, determined"},
 "Rohini":{"deity":"Brahma","symbol":"Chariot/ox-cart","gana":"Manushya","trait":"creative, sensual, magnetic"},
 "Mrigashira":{"deity":"Soma","symbol":"Deer's head","gana":"Deva","trait":"curious, gentle, searching"},
 "Ardra":{"deity":"Rudra","symbol":"Teardrop","gana":"Manushya","trait":"stormy, insightful, renewing"},
 "Punarvasu":{"deity":"Aditi","symbol":"Quiver of arrows","gana":"Deva","trait":"optimistic, wise, restoring"},
 "Pushya":{"deity":"Brihaspati","symbol":"Cow's udder/flower","gana":"Deva","trait":"nourishing, devout, steady"},
 "Ashlesha":{"deity":"Nagas","symbol":"Coiled serpent","gana":"Rakshasa","trait":"penetrating, mystical, strategic"},
 "Magha":{"deity":"Pitris","symbol":"Throne","gana":"Rakshasa","trait":"regal, honouring lineage, proud"},
 "Purva Phalguni":{"deity":"Bhaga","symbol":"Front of a bed","gana":"Manushya","trait":"warm, pleasure-loving, generous"},
 "Uttara Phalguni":{"deity":"Aryaman","symbol":"Back of a bed","gana":"Manushya","trait":"reliable, helpful, dignified"},
 "Hasta":{"deity":"Savitr","symbol":"Hand","gana":"Deva","trait":"skilful, clever, hands-on"},
 "Chitra":{"deity":"Tvashtar","symbol":"Bright jewel","gana":"Rakshasa","trait":"artistic, brilliant, charismatic"},
 "Swati":{"deity":"Vayu","symbol":"Young shoot in wind","gana":"Deva","trait":"independent, adaptable, balanced"},
 "Vishakha":{"deity":"Indra-Agni","symbol":"Triumphal arch","gana":"Rakshasa","trait":"goal-driven, ambitious, focused"},
 "Anuradha":{"deity":"Mitra","symbol":"Lotus","gana":"Deva","trait":"friendly, devoted, cooperative"},
 "Jyeshtha":{"deity":"Indra","symbol":"Umbrella/earring","gana":"Rakshasa","trait":"protective, senior, responsible"},
 "Mula":{"deity":"Nirriti","symbol":"Tied roots","gana":"Rakshasa","trait":"investigative, uprooting, philosophical"},
 "Purva Ashadha":{"deity":"Apas","symbol":"Fan/winnowing basket","gana":"Manushya","trait":"invincible, persuasive, proud"},
 "Uttara Ashadha":{"deity":"Vishvedevas","symbol":"Elephant tusk","gana":"Manushya","trait":"principled, enduring, victorious"},
 "Shravana":{"deity":"Vishnu","symbol":"Ear/three footprints","gana":"Deva","trait":"listening, learned, connective"},
 "Dhanishta":{"deity":"Vasus","symbol":"Drum","gana":"Rakshasa","trait":"rhythmic, wealthy, energetic"},
 "Shatabhisha":{"deity":"Varuna","symbol":"Empty circle","gana":"Rakshasa","trait":"healing, secretive, independent"},
 "Purva Bhadrapada":{"deity":"Aja Ekapada","symbol":"Front of funeral cot","gana":"Manushya","trait":"idealistic, intense, transformative"},
 "Uttara Bhadrapada":{"deity":"Ahir Budhnya","symbol":"Back of funeral cot","gana":"Manushya","trait":"deep, wise, calm"},
 "Revati":{"deity":"Pushan","symbol":"Fish/drum","gana":"Deva","trait":"nurturing, guiding, gentle"},
}
